http:
  port: "8081"
  host: "localhost"
  
url:
  basepath: "/api"
  getSlots: "/getSlots"
  postSlots: "/addSlots"
  bookSlot: "/bookSlot"
  
db:
  url: "jdbc:postgresql://localhost:5432/slot-booking"
  driver: "org.postgresql.Driver"
  user: "![hoqVh3jRhxsC16jyCdMf5g==]"  #"postgres"  
  password: "![ACZ2hhdcMS3TH0dtTGYzrw==]"   #"Apisero@123" 